dist: focal
sudo: false
language: node_js
node_js:
  - "10"

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./webapp/node_modules

install:
  - cd webapp && npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
