# Sample docker-compose for testing purpose. Most likely you would
# need to adapt in production environment ( SSL ...)

version: "3.9"

services:
  olympus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  rtmp:
    build:
      context: docker
      dockerfile: Dockerfile.rtmp
    ports:
      - "1935:1935"
    volumes:
      - srv-data:/srv

  nginx:
    build:
      context: docker
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    volumes:
      - srv-data:/srv

volumes:
  srv-data:
