//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"
)

func main() {
	if err := execute(); err != nil {
		log.Fatalf("could not generate version: %s", err)
	}
}

func execute() error {
	version, err := fetch_version_from_git()
	if err != nil {
		return err
	}
	fmt.Printf("OLYMPUS_VERSION:%s\n", version)
	if err := write_version_file(version, version_go_template, "version.go"); err != nil {
		return err
	}
	return write_version_file(version, version_angular_template, "../../webapp/src/environments/version.ts")
}

func fetch_version_from_git() (string, error) {
	cmd := exec.Command("git", "describe")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("`git describe` failed: %w, %s", err, out)
	}
	return strings.TrimSpace(string(out)), nil
}

var version_go_template = template.Must(template.New("").Parse(`// Code generated by go generate DO NOT EDIT.

package olympus

// Current package version
var OLYMPUS_VERSION = "{{.Version}}"
`))

var version_angular_template = template.Must(template.New("").Parse(`// Code generated by go generate DO NOT EDIT.

export const olympus_version = '{{.Version}}';
`))

func write_version_file(version string, tpl *template.Template, filepath string) error {
	f, err := os.Create(filepath)
	if err != nil {
		return err
	}
	defer f.Close()
	return tpl.Execute(f, struct {
		Timestamp time.Time
		Version   string
	}{Timestamp: time.Now(), Version: version})
}
