name: Create and publish a Docker image
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    pull_request:
      branches:
        - 'master'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - run: go run generate_version.go

      - name: Collect docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: formicidaetracker/olympus

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{github.event_name != 'pull_request' }}
          tags: ${{steps.meta.output.tags }}
          labels: ${{steps.meta.output.labels }}
